// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/proto/svc-client/client.proto

package svc_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	GetDataClient(ctx context.Context, in *GetDataClientRequest, opts ...grpc.CallOption) (*GetDataClientResponse, error)
	SaveDataClient(ctx context.Context, in *SaveDataClientRequest, opts ...grpc.CallOption) (*SaveDataClientResponse, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) GetDataClient(ctx context.Context, in *GetDataClientRequest, opts ...grpc.CallOption) (*GetDataClientResponse, error) {
	out := new(GetDataClientResponse)
	err := c.cc.Invoke(ctx, "/client.ClientService/GetDataClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) SaveDataClient(ctx context.Context, in *SaveDataClientRequest, opts ...grpc.CallOption) (*SaveDataClientResponse, error) {
	out := new(SaveDataClientResponse)
	err := c.cc.Invoke(ctx, "/client.ClientService/SaveDataClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility
type ClientServiceServer interface {
	GetDataClient(context.Context, *GetDataClientRequest) (*GetDataClientResponse, error)
	SaveDataClient(context.Context, *SaveDataClientRequest) (*SaveDataClientResponse, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (UnimplementedClientServiceServer) GetDataClient(context.Context, *GetDataClientRequest) (*GetDataClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataClient not implemented")
}
func (UnimplementedClientServiceServer) SaveDataClient(context.Context, *SaveDataClientRequest) (*SaveDataClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDataClient not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_GetDataClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetDataClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.ClientService/GetDataClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetDataClient(ctx, req.(*GetDataClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_SaveDataClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDataClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).SaveDataClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.ClientService/SaveDataClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).SaveDataClient(ctx, req.(*SaveDataClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDataClient",
			Handler:    _ClientService_GetDataClient_Handler,
		},
		{
			MethodName: "SaveDataClient",
			Handler:    _ClientService_SaveDataClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/svc-client/client.proto",
}
